[build]
  command = "npm run build"
  publish = "build"

[context.production]
  environment = { NODE_ENV = "production", NPM_FLAGS = "--legacy-peer-deps" }

[context.deploy-preview]
  environment = { NODE_ENV = "production", NPM_FLAGS = "--legacy-peer-deps" }
